$ANSIBLE_VAULT;1.1;AES256
62393834386663383332663639313932333862383035326637633438393831336166373364386166
3436616131336633323534393537653865386439306361310a616237353936656432376430363939
64643539326531633735363434653935636231336136376134313932323031373038366465373930
6132646432653462350a353438313230663362373933393434373564663139316238666462646439
61316439313236656164653835613730373662323036653565613430633337336463
